# crawler_config.yaml

# 검색할 키워드 리스트
search_keyword:
  - KDX한국데이터거래소

# 사용할 뉴스 소스 리스트
news_source:
  - mk

# 소스별 최대 크롤링 기사 수
max_articles_per_source: 100

# 오늘로부터 과거 몇 일치까지 크롤링할지 (정수)
date_range_days: 730